#!/usr/bin/env python
#
# Copyright (c) 2019 Opticks Team. All Rights Reserved.
#
# This file is part of Opticks
# (see https://bitbucket.org/simoncblyth/opticks).
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License.  
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
# See the License for the specific language governing permissions and 
# limitations under the License.
#

"""
Aiming for this to be generated, so keep it simple
"""
import numpy as np
from opticks.ana.shape import X, SEllipsoid, STubs, STorus, SCons, SSubtractionSolid, SUnionSolid, SIntersectionSolid


class x020(X):
    """
    // LV=20
    // start portion generated by nnode::to_g4code 
    G4VSolid* make_solid()
    { 
        G4VSolid* c = new G4Ellipsoid("PMT_20inch_body_solid_1_Ellipsoid0x4c81db0", 254.000000, 254.000000, 184.000000, -184.000000, 184.000000) ; // 2
        G4VSolid* f = new G4Tubs("PMT_20inch_body_solid_2_Tube0x4c81e90", 0.000000, 77.976127, 21.496692, 0.000000, CLHEP::twopi) ; // 3
        G4VSolid* h = new G4Torus("PMT_20inch_body_solid_2_Torus0x4c81fc0", 0.000000, 47.010000, 97.000000, -0.000175, CLHEP::twopi) ; // 3
        
        G4ThreeVector A(0.000000,0.000000,-21.486692);
        G4VSolid* e = new G4SubtractionSolid("PMT_20inch_body_solid_part20x4c820b0", f, h, NULL, A) ; // 2
        
        G4ThreeVector B(0.000000,0.000000,-197.513308);
        G4VSolid* b = new G4UnionSolid("PMT_20inch_body_solid_1_20x4c90cd0", c, e, NULL, B) ; // 1
        G4VSolid* j = new G4Tubs("PMT_20inch_body_solid_3_EndTube0x4c90ba0", 0.000000, 50.010000, 60.010000, 0.000000, CLHEP::twopi) ; // 1
        
        G4ThreeVector C(0.000000,0.000000,-279.000000);
        G4VSolid* a = new G4UnionSolid("PMT_20inch_body_solid0x4c90e50", b, j, NULL, C) ; // 0
        return a ; 
    } 
    // end portion generated by nnode::to_g4code 

    """
    def __init__(self):
        c = SEllipsoid( "c", [254.000, 184.000 ] )
        f = STubs(      "f", [77.976127, 21.496692] )
        h = STorus(     "h", [ 47.010000, 97.000000] )

        A = np.array( [0, -21.486692] )
        e = SSubtractionSolid( "e" , [f, h, A] )

        B = np.array( [0, -197.513308] )  
        b = SUnionSolid( "b", [c, e, B] )
         
        j = STubs( "j", [50.010000, 60.010000] )
        C = np.array( [0, -279.000000] )
        a = SUnionSolid( "a", [b, j, C] )

        self.root = a 
        self.prims = [c,f,h,j]   



if __name__ == '__main__':
    x = x020()
    print(repr(x))

