#!/usr/bin/env python
"""
Aiming for this to be generated, so keep it simple
"""
import numpy as np
from opticks.ana.shape import X, Ellipsoid, Tubs, Torus, Cons, SubtractionSolid, UnionSolid, IntersectionSolid


class x021(X):
    """
    // LV=21
    // start portion generated by nnode::to_g4code 
    G4VSolid* make_solid()
    { 
        G4VSolid* c = new G4Ellipsoid("PMT_20inch_pmt_solid_1_Ellipsoid0x4c3bc00", 254.001000, 254.001000, 184.001000, -184.001000, 184.001000) ; // 2
        G4VSolid* f = new G4Tubs("PMT_20inch_pmt_solid_2_Tube0x4c3bc90", 0.000000, 77.976532, 21.496235, 0.000000, CLHEP::twopi) ; // 3
        G4VSolid* h = new G4Torus("PMT_20inch_pmt_solid_2_Torus0x4c84bd0", 0.000000, 47.009000, 97.000000, -0.000175, CLHEP::twopi) ; // 3
        
        G4ThreeVector A(0.000000,0.000000,-21.486235);
        G4VSolid* e = new G4SubtractionSolid("PMT_20inch_pmt_solid_part20x4c84c70", f, h, NULL, A) ; // 2
           
        G4ThreeVector B(0.000000,0.000000,-197.513765);
        G4VSolid* b = new G4UnionSolid("PMT_20inch_pmt_solid_1_20x4c84f90", c, e, NULL, B) ; // 1
        G4VSolid* j = new G4Tubs("PMT_20inch_pmt_solid_3_EndTube0x4c84e60", 0.000000, 50.011000, 60.010500, 0.000000, CLHEP::twopi) ; // 1
           
        G4ThreeVector C(0.000000,0.000000,-279.000500);
        G4VSolid* a = new G4UnionSolid("PMT_20inch_pmt_solid0x4c81b40", b, j, NULL, C) ; // 0
        return a ; 
    } 
    // end portion generated by nnode::to_g4code 
    """
    def __init__(self):
        c = Ellipsoid( "c", [254.001000, 184.001000] )
        f = Tubs(     "f", [77.976532, 21.496235] )
        h = Torus(    "h", [47.009000, 97.000000] )

        A = np.array( [0.000000,-21.486235] )
        e = SubtractionSolid( "e" , [f, h, A] )

        B = np.array( [0.000000,-197.513765])
        b = UnionSolid( "b", [c, e, B] )
         
        j = Tubs( "j", [50.011000, 60.010500] )
        C = np.array( [0.000000,-279.000500] )
        a = UnionSolid( "a", [b, j, C] )

        self.root = a 



if __name__ == '__main__':
    x = x021()
    print(repr(x))

    c = x.find("Ellipsoid")
    print(repr(c))

    import copy 
    xc = copy.deepcopy(x)
    print(repr(xc))


