#!/usr/bin/env python
#
# Copyright (c) 2019 Opticks Team. All Rights Reserved.
#
# This file is part of Opticks
# (see https://bitbucket.org/simoncblyth/opticks).
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License.  
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
# See the License for the specific language governing permissions and 
# limitations under the License.
#

"""
Aiming for this to be generated, so keep it simple
"""
import numpy as np
from opticks.ana.shape import X, SEllipsoid, STubs, STorus, SCons, SSubtractionSolid, SUnionSolid, SIntersectionSolid


class x021(X):
    """
    // LV=21
    // start portion generated by nnode::to_g4code 
    G4VSolid* make_solid()
    { 
        G4VSolid* c = new G4Ellipsoid("PMT_20inch_pmt_solid_1_Ellipsoid0x4c3bc00", 254.001000, 254.001000, 184.001000, -184.001000, 184.001000) ; // 2
        G4VSolid* f = new G4Tubs("PMT_20inch_pmt_solid_2_Tube0x4c3bc90", 0.000000, 77.976532, 21.496235, 0.000000, CLHEP::twopi) ; // 3
        G4VSolid* h = new G4Torus("PMT_20inch_pmt_solid_2_Torus0x4c84bd0", 0.000000, 47.009000, 97.000000, -0.000175, CLHEP::twopi) ; // 3
        
        G4ThreeVector A(0.000000,0.000000,-21.486235);
        G4VSolid* e = new G4SubtractionSolid("PMT_20inch_pmt_solid_part20x4c84c70", f, h, NULL, A) ; // 2
           
        G4ThreeVector B(0.000000,0.000000,-197.513765);
        G4VSolid* b = new G4UnionSolid("PMT_20inch_pmt_solid_1_20x4c84f90", c, e, NULL, B) ; // 1
        G4VSolid* j = new G4Tubs("PMT_20inch_pmt_solid_3_EndTube0x4c84e60", 0.000000, 50.011000, 60.010500, 0.000000, CLHEP::twopi) ; // 1
           
        G4ThreeVector C(0.000000,0.000000,-279.000500);
        G4VSolid* a = new G4UnionSolid("PMT_20inch_pmt_solid0x4c81b40", b, j, NULL, C) ; // 0
        return a ; 
    } 
    // end portion generated by nnode::to_g4code 
    """
    def __init__(self):
        c = SEllipsoid( "c", [254.001000, 184.001000] )
        f = STubs(     "f", [77.976532, 21.496235] )
        h = STorus(    "h", [47.009000, 97.000000] )

        A = np.array( [0.000000,-21.486235] )
        e = SSubtractionSolid( "e" , [f, h, A] )

        B = np.array( [0.000000,-197.513765])
        b = SUnionSolid( "b", [c, e, B] )
         
        j = STubs( "j", [50.011000, 60.010500] )
        C = np.array( [0.000000,-279.000500] )
        a = SUnionSolid( "a", [b, j, C] )

        X.__init__(self, a )   # sets root



if __name__ == '__main__':
    x = x021()
    print(repr(x))

    c = x.find("SEllipsoid")
    print(repr(c))

    import copy 
    xc = copy.deepcopy(x)
    print(repr(xc))


