/*
 * Copyright (c) 2019 Opticks Team. All Rights Reserved.
 *
 * This file is part of Opticks
 * (see https://bitbucket.org/simoncblyth/opticks).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */

// generated by glfw-;glfw-keyname Sat Oct 27 21:31:56 CST 2018
const char* glfw_keyname( int key )
{
    const char* s = NULL ; 
    switch(key)
    {
        case GLFW_KEY_UNKNOWN               : s = "GLFW_KEY_UNKNOWN"             ; break ; 
        case GLFW_KEY_SPACE                 : s = "GLFW_KEY_SPACE"               ; break ; 
        case GLFW_KEY_APOSTROPHE            : s = "GLFW_KEY_APOSTROPHE"          ; break ; 
        case GLFW_KEY_COMMA                 : s = "GLFW_KEY_COMMA"               ; break ; 
        case GLFW_KEY_MINUS                 : s = "GLFW_KEY_MINUS"               ; break ; 
        case GLFW_KEY_PERIOD                : s = "GLFW_KEY_PERIOD"              ; break ; 
        case GLFW_KEY_SLASH                 : s = "GLFW_KEY_SLASH"               ; break ; 
        case GLFW_KEY_0                     : s = "GLFW_KEY_0"                   ; break ; 
        case GLFW_KEY_1                     : s = "GLFW_KEY_1"                   ; break ; 
        case GLFW_KEY_2                     : s = "GLFW_KEY_2"                   ; break ; 
        case GLFW_KEY_3                     : s = "GLFW_KEY_3"                   ; break ; 
        case GLFW_KEY_4                     : s = "GLFW_KEY_4"                   ; break ; 
        case GLFW_KEY_5                     : s = "GLFW_KEY_5"                   ; break ; 
        case GLFW_KEY_6                     : s = "GLFW_KEY_6"                   ; break ; 
        case GLFW_KEY_7                     : s = "GLFW_KEY_7"                   ; break ; 
        case GLFW_KEY_8                     : s = "GLFW_KEY_8"                   ; break ; 
        case GLFW_KEY_9                     : s = "GLFW_KEY_9"                   ; break ; 
        case GLFW_KEY_SEMICOLON             : s = "GLFW_KEY_SEMICOLON"           ; break ; 
        case GLFW_KEY_EQUAL                 : s = "GLFW_KEY_EQUAL"               ; break ; 
        case GLFW_KEY_A                     : s = "GLFW_KEY_A"                   ; break ; 
        case GLFW_KEY_B                     : s = "GLFW_KEY_B"                   ; break ; 
        case GLFW_KEY_C                     : s = "GLFW_KEY_C"                   ; break ; 
        case GLFW_KEY_D                     : s = "GLFW_KEY_D"                   ; break ; 
        case GLFW_KEY_E                     : s = "GLFW_KEY_E"                   ; break ; 
        case GLFW_KEY_F                     : s = "GLFW_KEY_F"                   ; break ; 
        case GLFW_KEY_G                     : s = "GLFW_KEY_G"                   ; break ; 
        case GLFW_KEY_H                     : s = "GLFW_KEY_H"                   ; break ; 
        case GLFW_KEY_I                     : s = "GLFW_KEY_I"                   ; break ; 
        case GLFW_KEY_J                     : s = "GLFW_KEY_J"                   ; break ; 
        case GLFW_KEY_K                     : s = "GLFW_KEY_K"                   ; break ; 
        case GLFW_KEY_L                     : s = "GLFW_KEY_L"                   ; break ; 
        case GLFW_KEY_M                     : s = "GLFW_KEY_M"                   ; break ; 
        case GLFW_KEY_N                     : s = "GLFW_KEY_N"                   ; break ; 
        case GLFW_KEY_O                     : s = "GLFW_KEY_O"                   ; break ; 
        case GLFW_KEY_P                     : s = "GLFW_KEY_P"                   ; break ; 
        case GLFW_KEY_Q                     : s = "GLFW_KEY_Q"                   ; break ; 
        case GLFW_KEY_R                     : s = "GLFW_KEY_R"                   ; break ; 
        case GLFW_KEY_S                     : s = "GLFW_KEY_S"                   ; break ; 
        case GLFW_KEY_T                     : s = "GLFW_KEY_T"                   ; break ; 
        case GLFW_KEY_U                     : s = "GLFW_KEY_U"                   ; break ; 
        case GLFW_KEY_V                     : s = "GLFW_KEY_V"                   ; break ; 
        case GLFW_KEY_W                     : s = "GLFW_KEY_W"                   ; break ; 
        case GLFW_KEY_X                     : s = "GLFW_KEY_X"                   ; break ; 
        case GLFW_KEY_Y                     : s = "GLFW_KEY_Y"                   ; break ; 
        case GLFW_KEY_Z                     : s = "GLFW_KEY_Z"                   ; break ; 
        case GLFW_KEY_LEFT_BRACKET          : s = "GLFW_KEY_LEFT_BRACKET"        ; break ; 
        case GLFW_KEY_BACKSLASH             : s = "GLFW_KEY_BACKSLASH"           ; break ; 
        case GLFW_KEY_RIGHT_BRACKET         : s = "GLFW_KEY_RIGHT_BRACKET"       ; break ; 
        case GLFW_KEY_GRAVE_ACCENT          : s = "GLFW_KEY_GRAVE_ACCENT"        ; break ; 
        case GLFW_KEY_WORLD_1               : s = "GLFW_KEY_WORLD_1"             ; break ; 
        case GLFW_KEY_WORLD_2               : s = "GLFW_KEY_WORLD_2"             ; break ; 
        case GLFW_KEY_ESCAPE                : s = "GLFW_KEY_ESCAPE"              ; break ; 
        case GLFW_KEY_ENTER                 : s = "GLFW_KEY_ENTER"               ; break ; 
        case GLFW_KEY_TAB                   : s = "GLFW_KEY_TAB"                 ; break ; 
        case GLFW_KEY_BACKSPACE             : s = "GLFW_KEY_BACKSPACE"           ; break ; 
        case GLFW_KEY_INSERT                : s = "GLFW_KEY_INSERT"              ; break ; 
        case GLFW_KEY_DELETE                : s = "GLFW_KEY_DELETE"              ; break ; 
        case GLFW_KEY_RIGHT                 : s = "GLFW_KEY_RIGHT"               ; break ; 
        case GLFW_KEY_LEFT                  : s = "GLFW_KEY_LEFT"                ; break ; 
        case GLFW_KEY_DOWN                  : s = "GLFW_KEY_DOWN"                ; break ; 
        case GLFW_KEY_UP                    : s = "GLFW_KEY_UP"                  ; break ; 
        case GLFW_KEY_PAGE_UP               : s = "GLFW_KEY_PAGE_UP"             ; break ; 
        case GLFW_KEY_PAGE_DOWN             : s = "GLFW_KEY_PAGE_DOWN"           ; break ; 
        case GLFW_KEY_HOME                  : s = "GLFW_KEY_HOME"                ; break ; 
        case GLFW_KEY_END                   : s = "GLFW_KEY_END"                 ; break ; 
        case GLFW_KEY_CAPS_LOCK             : s = "GLFW_KEY_CAPS_LOCK"           ; break ; 
        case GLFW_KEY_SCROLL_LOCK           : s = "GLFW_KEY_SCROLL_LOCK"         ; break ; 
        case GLFW_KEY_NUM_LOCK              : s = "GLFW_KEY_NUM_LOCK"            ; break ; 
        case GLFW_KEY_PRINT_SCREEN          : s = "GLFW_KEY_PRINT_SCREEN"        ; break ; 
        case GLFW_KEY_PAUSE                 : s = "GLFW_KEY_PAUSE"               ; break ; 
        case GLFW_KEY_F1                    : s = "GLFW_KEY_F1"                  ; break ; 
        case GLFW_KEY_F2                    : s = "GLFW_KEY_F2"                  ; break ; 
        case GLFW_KEY_F3                    : s = "GLFW_KEY_F3"                  ; break ; 
        case GLFW_KEY_F4                    : s = "GLFW_KEY_F4"                  ; break ; 
        case GLFW_KEY_F5                    : s = "GLFW_KEY_F5"                  ; break ; 
        case GLFW_KEY_F6                    : s = "GLFW_KEY_F6"                  ; break ; 
        case GLFW_KEY_F7                    : s = "GLFW_KEY_F7"                  ; break ; 
        case GLFW_KEY_F8                    : s = "GLFW_KEY_F8"                  ; break ; 
        case GLFW_KEY_F9                    : s = "GLFW_KEY_F9"                  ; break ; 
        case GLFW_KEY_F10                   : s = "GLFW_KEY_F10"                 ; break ; 
        case GLFW_KEY_F11                   : s = "GLFW_KEY_F11"                 ; break ; 
        case GLFW_KEY_F12                   : s = "GLFW_KEY_F12"                 ; break ; 
        case GLFW_KEY_F13                   : s = "GLFW_KEY_F13"                 ; break ; 
        case GLFW_KEY_F14                   : s = "GLFW_KEY_F14"                 ; break ; 
        case GLFW_KEY_F15                   : s = "GLFW_KEY_F15"                 ; break ; 
        case GLFW_KEY_F16                   : s = "GLFW_KEY_F16"                 ; break ; 
        case GLFW_KEY_F17                   : s = "GLFW_KEY_F17"                 ; break ; 
        case GLFW_KEY_F18                   : s = "GLFW_KEY_F18"                 ; break ; 
        case GLFW_KEY_F19                   : s = "GLFW_KEY_F19"                 ; break ; 
        case GLFW_KEY_F20                   : s = "GLFW_KEY_F20"                 ; break ; 
        case GLFW_KEY_F21                   : s = "GLFW_KEY_F21"                 ; break ; 
        case GLFW_KEY_F22                   : s = "GLFW_KEY_F22"                 ; break ; 
        case GLFW_KEY_F23                   : s = "GLFW_KEY_F23"                 ; break ; 
        case GLFW_KEY_F24                   : s = "GLFW_KEY_F24"                 ; break ; 
        case GLFW_KEY_F25                   : s = "GLFW_KEY_F25"                 ; break ; 
        case GLFW_KEY_KP_0                  : s = "GLFW_KEY_KP_0"                ; break ; 
        case GLFW_KEY_KP_1                  : s = "GLFW_KEY_KP_1"                ; break ; 
        case GLFW_KEY_KP_2                  : s = "GLFW_KEY_KP_2"                ; break ; 
        case GLFW_KEY_KP_3                  : s = "GLFW_KEY_KP_3"                ; break ; 
        case GLFW_KEY_KP_4                  : s = "GLFW_KEY_KP_4"                ; break ; 
        case GLFW_KEY_KP_5                  : s = "GLFW_KEY_KP_5"                ; break ; 
        case GLFW_KEY_KP_6                  : s = "GLFW_KEY_KP_6"                ; break ; 
        case GLFW_KEY_KP_7                  : s = "GLFW_KEY_KP_7"                ; break ; 
        case GLFW_KEY_KP_8                  : s = "GLFW_KEY_KP_8"                ; break ; 
        case GLFW_KEY_KP_9                  : s = "GLFW_KEY_KP_9"                ; break ; 
        case GLFW_KEY_KP_DECIMAL            : s = "GLFW_KEY_KP_DECIMAL"          ; break ; 
        case GLFW_KEY_KP_DIVIDE             : s = "GLFW_KEY_KP_DIVIDE"           ; break ; 
        case GLFW_KEY_KP_MULTIPLY           : s = "GLFW_KEY_KP_MULTIPLY"         ; break ; 
        case GLFW_KEY_KP_SUBTRACT           : s = "GLFW_KEY_KP_SUBTRACT"         ; break ; 
        case GLFW_KEY_KP_ADD                : s = "GLFW_KEY_KP_ADD"              ; break ; 
        case GLFW_KEY_KP_ENTER              : s = "GLFW_KEY_KP_ENTER"            ; break ; 
        case GLFW_KEY_KP_EQUAL              : s = "GLFW_KEY_KP_EQUAL"            ; break ; 
        case GLFW_KEY_LEFT_SHIFT            : s = "GLFW_KEY_LEFT_SHIFT"          ; break ; 
        case GLFW_KEY_LEFT_CONTROL          : s = "GLFW_KEY_LEFT_CONTROL"        ; break ; 
        case GLFW_KEY_LEFT_ALT              : s = "GLFW_KEY_LEFT_ALT"            ; break ; 
        case GLFW_KEY_LEFT_SUPER            : s = "GLFW_KEY_LEFT_SUPER"          ; break ; 
        case GLFW_KEY_RIGHT_SHIFT           : s = "GLFW_KEY_RIGHT_SHIFT"         ; break ; 
        case GLFW_KEY_RIGHT_CONTROL         : s = "GLFW_KEY_RIGHT_CONTROL"       ; break ; 
        case GLFW_KEY_RIGHT_ALT             : s = "GLFW_KEY_RIGHT_ALT"           ; break ; 
        case GLFW_KEY_RIGHT_SUPER           : s = "GLFW_KEY_RIGHT_SUPER"         ; break ; 
        case GLFW_KEY_MENU                  : s = "GLFW_KEY_MENU"                ; break ; 
    }
    return s ; 
}
