#!/bin/bash -l

export X4SolidMaker_GeneralSphereDEV_innerRadius=50
export X4SolidMaker_GeneralSphereDEV_outerRadius=100
export X4SolidMaker_GeneralSphereDEV_phiStart=0
export X4SolidMaker_GeneralSphereDEV_phiDelta=0.5
export X4SolidMaker_GeneralSphereDEV_thetaStart=0.25
export X4SolidMaker_GeneralSphereDEV_thetaDelta=0.75



