#pragma once

#include "X4_API_EXPORT.hh"
#include "X4Entity.hh"
#include "X4SolidBase.hh"


class G4Cons ; 
class G4Trd ; 
class G4Tubs ; 
class G4Sphere ; 
class G4Orb ; 


class G4VSolid ; 
template <typename T> class NPY ;
class X4Mesh ; 

struct nnode ; 


/**
X4SolidBase
=============

NB : the below generated convert implementation standins 
that assert on being called are intended to be left asis.  
Just implement overriding convert methods up in X4Solid, as
you handle each solid.

**/

class X4_API X4SolidBase 
{
    public:
        static G4Cons*   MakeCone(const char* name, float z, float rmax1, float rmax2, float rmin1=0.f, float rmin2=0.f, float startphi=0.f, float deltaphi=360.f );
        static G4Trd*    MakeTrapezoidCube(const char* name, float sz);
        static G4Trd*    MakeTrapezoid(const char* name, float z,  float x1, float y1, float x2, float y2 );
        static G4Tubs*   MakeTubs(const char* name, float rmin, float rmax, float hz, float startphi=0.f, float deltaphi=360.f );
        static G4Orb*    MakeOrb(const char* name, float radius);
        static G4Sphere* MakeSphere(const char* name, float rmax, float rmin=0.f );
        static G4Sphere* MakeZSphere(const char* name, float rmax, float rmin=0.f, float startTheta=0.f, float deltaTheta=180.f );
    public:
        X4SolidBase(const G4VSolid* solid); 
        nnode* root() const ;
        std::string desc() const  ; 
    private:
        void init();
    protected:
        void setRoot(nnode* root);
    protected:
        // generated by x4-convert-hh- Mon Jun 11 20:43:47 HKT 2018 

        void convertBooleanSolid();
        void convertMultiUnion();
        void convertBox();
        void convertCons();
        void convertEllipticalCone();
        void convertEllipsoid();
        void convertEllipticalTube();
        void convertExtrudedSolid();
        void convertHype();
        void convertOrb();
        void convertPara();
        void convertParaboloid();
        void convertPolycone();
        void convertGenericPolycone();
        void convertPolyhedra();
        void convertSphere();
        void convertTessellatedSolid();
        void convertTet();
        void convertTorus();
        void convertGenericTrap();
        void convertTrap();
        void convertTrd();
        void convertTubs();
        void convertCutTubs();
        void convertTwistedBox();
        void convertTwistedTrap();
        void convertTwistedTrd();
        void convertTwistedTubs();

    protected:
        const G4VSolid* m_solid ;  
        const char*     m_name ; 
        X4Mesh*         m_mesh ;
        X4Entity_t      m_entityType ; 
        const char*     m_entityName ; 
        nnode*          m_root ; 
};

