#pragma once

#include "X4_API_EXPORT.hh"
#include "X4Entity.hh"
#include "X4SolidBase.hh"

class G4VSolid ; 
class G4Sphere ; 
template <typename T> class NPY ;
class X4Mesh ; 

struct nnode ; 


/**
X4SolidBase
=============

NB : the below generated convert implementation standins 
that assert on being called are intended to be left asis.  
Just implement overriding convert methods up in X4Solid, as
you handle each solid.

**/

class X4_API X4SolidBase 
{
    public:
        static G4Sphere* MakeSphere(const char* name);
    public:
        X4SolidBase(const G4VSolid* solid); 
        nnode* root() const ;
        std::string desc() const  ; 
    private:
        void init();
    protected:
        void setRoot(nnode* root);
    protected:
        // generated by x4-convert-hh- Mon Jun 11 20:43:47 HKT 2018 

        void convertBooleanSolid();
        void convertMultiUnion();
        void convertBox();
        void convertCons();
        void convertEllipticalCone();
        void convertEllipsoid();
        void convertEllipticalTube();
        void convertExtrudedSolid();
        void convertHype();
        void convertOrb();
        void convertPara();
        void convertParaboloid();
        void convertPolycone();
        void convertGenericPolycone();
        void convertPolyhedra();
        void convertSphere();
        void convertTessellatedSolid();
        void convertTet();
        void convertTorus();
        void convertGenericTrap();
        void convertTrap();
        void convertTrd();
        void convertTubs();
        void convertCutTubs();
        void convertTwistedBox();
        void convertTwistedTrap();
        void convertTwistedTrd();
        void convertTwistedTubs();

    protected:
        const G4VSolid* m_solid ;  
        X4Mesh*         m_mesh ;
        X4Entity_t      m_entityType ; 
        const char*     m_entityName ; 
        nnode*          m_root ; 
};

